### ISSUE TITLE
how best to include output if error/warn

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#10]
Would be nice to give users of the API some of the actual output if there are check failures/warnings. However, not sure how to include e.g, this 

<img width="782" alt="screen shot 2017-10-13 at 9 30 24 am" src="https://user-images.githubusercontent.com/577668/31556289-2ffde1a4-aff9-11e7-9f33-626215c4531a.png">

in JSON 🤔

**Comment by gaborcsardi** [comment]
I guess 

```
Version: 1.1.2 
Check: installed package size 
Result: NOTE 
     installed size is 17.3Mb
     sub-directories of 1Mb or more:
     help 1.1Mb
     libs 15.2Mb 
Flavors: r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-windows-ix86+x86_64, r-patched-solaris-x86, r-release-windows-ix86+x86_64, r-release-osx-x86_64, r-oldrel-windows-ix86+x86_64, r-oldrel-osx-x86_64
```
could become
```json
{ 
  "Version": "1.1.2",
  "Check": "installed package size",
  "Result": "NOTE",
  "Output": "installed size is 17.3Mb\nsub-directories of 1Mb or more:\nhelp 1.1Mb\nlibs 15.2Mb\n",
  "Flavors": ["r-devel-linux-x86_64-fedora-clang", 
              "r-devel-linux-x86_64-fedora-gcc", 
              "r-devel-windows-ix86+x86_64", 
              "r-patched-solaris-x86", 
              "r-release-windows-ix86+x86_64",
              "r-release-osx-x86_64", 
              "r-oldrel-windows-ix86+x86_64",
              "r-oldrel-osx-x86_64"]
}
```

But don't worry about it too much, because I am sure that some packages look different. Just having the numbers is already a pretty good first step.

**Comment by sckott** [comment]
That looks good to me. There seems to be lots of variation, in the output, but could probably make a parser flexible enough. Will have a play later on

**Comment by gaborcsardi** [comment]
Yeah, I think you could have a simple parser, and if a package does not parse, you just catch the error, and include "Unknown error" or sg like that.

**Comment by sckott** [comment]
yeah, sounds good

**Comment by sckott** [comment]
done now, closing
