### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#13]
Want to allow people to opt in to notifications of various kinds to find out when theres notes/warnings/errors on their pkgs on cran checks. 

Options:

- email
- twitter?
- slack?
- any others?

Probably should set up super minimal website for it. Pick which type of notification, which pkgs, on what type (warn/note/error).

**Comment by gaborcsardi** [comment]
Instead of a web-site you could also just have an R package, and a web-api.

**Comment by sckott** [comment]
Good point. My hunch is that if people have to check their cran check results they probably will forget - notifications would make it easy. If that's the way we go, we'd need some way for a person to opt in to notifications. I guess this opt in could be just an API route, so users could do it in cli, or via an R pkg

**Comment by PeterMTaylor** [comment]
I would be interested if this notification could flag packages that vary in licenses such that one is MIT license and another is GPL license, I’m sure already offered on Github but note sure if CRAN follows suit.

This notification could give some self esteem back to programmers who may be developing R code that needs to be aware that certain packages could eventually “switch” to another.

**Comment by sckott** [comment]
Thanks @PeterMTaylor for your interest - that's a good idea in general, but the scope here is only related to notifications for CRAN check results - should have been more clear about that

**Comment by noamross** [comment]
Per discussion elsewhere, we'd like to sign up rOpenSci package authors for this on acceptance (with opt-out - emails should have a prominent link for turning them off).  Packages may not be on CRAN when they are accepted to RO but we should automatically watch for them to arrive and start notifications then.

**Comment by sckott** [comment]
Thanks @noamross - Sounds right to opt-in since we want maintainers to get ahead of cran checks problems. I guess we can just use the maintainer email address in the DESCRIPTION file

**Comment by maelle** [comment]
Should this be re-opened because of " Sounds right to opt-in since we want maintainers to get ahead of cran checks problems. I guess we can just use the maintainer email address in the DESCRIPTION file"? Or a new issue? This issue was linked from the package curation draft policy.

**Comment by sckott** [comment]
let's open a new issue for that.
