### ISSUE TITLE
Badges?

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/cchecksapi#16]
Maybe a single combined badge that shows the "worst" result? 

FWIW here is some example badge generation code. Different language, but maybe still useful:
https://github.com/metacran/metacranweb/blob/8e930ab92c2f73c0cef4c3f64cf9ae208aa0bb9f/routes/badges.js

**Comment by sckott** [comment]
Good idea.  Similarly, I need to add https://github.com/ropensci/cchecksapi/issues/12 in the JSON response. 

your JS code seems simple enough. thanks!

**Comment by sckott** [comment]
@gaborcsardi okay, first draft running on server

https://github.com/ropensci/cchecksapi/tree/badges#badges

e..g, 

https://cranchecks.info/badges/clean/processx
https://cranchecks.info/badges/flavor/r-oldrel-osx-x86_64/processx
https://cranchecks.info/badges/flavor/r-release-osx-x86_64/cdcfluview

I still need to 

- fix sizing of badges relative to text
- add support for other proposed routes: `/badges/worst/:package`, `/badges/noerrors/:package`, `/badges/nowarns/:package`, `/badges/nonotes/:package`

Not sure where to suggest to link to from badges. Could be this API, or the cran check page or something else?

**Comment by gaborcsardi** [comment]
Super cool! I would just have "CRAN" as the badge label, because I think  "Cchecks" is a bit mystical.

Can we also have a badge that is just `[CRAN|OK]`, `[CRAN|NOTE]`, etc. in the right color? Or that's the "worst" badge maybe?

Personally,  I think the flavors  are not super important, especially because occasionally they change, and then it is hard to create a stable badge URL. Maybe some meta flavors, like "Windows", "Linux", "macOS" and "Solaris" would make sense? I.e. "Linux" would show the worst outcome of any Linux flavors, etc.

For linking, I think people could link to the main cran page, or the cran check page, maybe?

Btw. it would be great to be able to ignore some check results, because  e.g. the processx NOTE will never be fixed, and the package is perfectly fine. I am not sure what cchecksapi can do here, just bringing it up...

**Comment by sckott** [comment]
Okay, was thinking it should be set apart from yours but if you're okay with that, then i can do that. 

> Can we also have a badge that is just ...

Yeah, I think that's what I had in mind for the `/badges/worst/:package` route. Sound good?

I agree that meta-flavors might be useful. can do that instead

Will think more about where to link

> it would be great to be able to ignore some check results

maybe via a query parameter?  e.g., `?ignore=r-oldrel-osx-x86_64` or `?ignore=osx`

**Comment by gaborcsardi** [comment]
> Okay, was thinking it should be set apart from yours but if you're okay with that, then i can do that.

Yeah, it will set apart, because one is a version number, the other is OK, NOTE, etc.

>  Yeah, I think that's what I had in mind for the /badges/worst/:package route. Sound good?

Yep!

> maybe via a query parameter? e.g., ?ignore=r-oldrel-osx-x86_64 or ?ignore=osx

I was actually thinking about some whitelisting based on the actual failure. Because e.g. here I get a  lot of NOTEs just for the package size: https://cran.rstudio.com/web/checks/check_results_igraph.html

This is not trivial to implement of course, I think for now, maybe a query parameter to `badges/worst/:package` that just ignores all NOTEs would be good enough. I think a WARNING is usually not sg you would want to ignore.

**Comment by sckott** [comment]
Okay, updated, any other thoughts before I merge to master?

**Comment by gaborcsardi** [comment]
Super cool! Starting to add it to READMEs right now!
