### ISSUE TITLE
fix how we ge pkg names

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#17]
right now we're topping out at 12K

**Comment by gaborcsardi** [comment]
What exactly is topping out?

**Comment by sckott** [comment]
i have the code to get pkg names kind of hard coded https://github.com/ropensci/cchecksapi/blob/master/scrape.rb#L91-L108 - working on a while loop now

**Comment by sckott** [comment]
limit max is 6000, correct?

**Comment by gaborcsardi** [comment]
Why not just get them in one query? This code is not live, right?

**Comment by gaborcsardi** [comment]
Btw. I can add an API point that just lists all package names.

**Comment by sckott** [comment]
i thought there was a max for `limit`, but maybe not? 

yeah, an endpt to just list pkgs would be helpful

**Comment by sckott** [comment]
fix in for  now

**Comment by gaborcsardi** [comment]
http://crandb.r-pkg.org/-/pkgnames?limit=10

FYI, just a second or so to get all names...
