### ISSUE TITLE
Badges state

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#28]
Is it binary is it OK vs not OK?

**Comment by sckott** [comment]
can you clarify. it depends on the badges route used

**Comment by maelle** [comment]
I had tried `[![cran checks](https://cranchecks.info/badges/summary/reshape)](https://cran.r-project.org/web/checks/check_results_reshape.html)`. https://github.com/ropensci/cchecksapi#badges

**Comment by sckott** [comment]
im confused.

**Comment by maelle** [comment]
Sorry what I mean is I wonder what color code there is.
Just
* green "OK"
* red "not OK" for any NOTE/WARNING/ERROR?
I had tried it for `av` [![cran checks](https://cranchecks.info/badges/summary/av)](https://cran.r-project.org/web/checks/check_results_av.html)

**Comment by sckott** [comment]
correct, 

green = OK
red = NOT OK

**Comment by maelle** [comment]
Which might mean some developers won't want to adopt them?

**Comment by sckott** [comment]
perhaps we could allow passing a color as a parameter like Gabor does for his badges. 

I think it makes sense to keep the defaults as is, e.g., travis has the same colors, or no?

**Comment by gaborcsardi** [comment]
Ideally we would be able to whitelist some NOTEs. But that's quite hard to implement.

**Comment by sckott** [comment]
Right, perhaps categorize NOTEs into types and then allow parameter passed in to say which types of NOTEs to ignore?

**Comment by gaborcsardi** [comment]
I think we should just start easy, and ignore some, e.g. the one about the package size, for a start. If  CRAN is OK with the NOTE, then the package author will be OK as well.

**Comment by gaborcsardi** [comment]
I mean when I say "we", I mean, _if I were you_.

**Comment by sckott** [comment]
moving conversation to new issue
