### ISSUE TITLE
history: collect all history ?

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#30]
In addition to new history routes, maybe push all history data to disk and provide a dump?  so when history data is 30 days old purge from mongo and compress onto disk - so a file for each date, like

- `cran-checks-2018-10-01.json`
- `cran-checks-2018-10-02.json`
- `cran-checks-2018-10-03.json`
- and so on

then a route for requesting these files 

`/pkghistory/:date:` - e.g., `/pkghistory/2018-10-01`

**Comment by maelle** [comment]
how is the history saved at the moment?

**Comment by sckott** [comment]
its pushed into a SQL database and then you can get to history for individual pkgs for now, but not history across pkgs

**Comment by maelle** [comment]
Ok, I saw this route, very cool.
