### ISSUE TITLE
scraping maintainers: use gabor's api

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#39]
see https://github.com/metacran/crandb/issues/45#issuecomment-479156171 

right now in https://github.com/ropensci/cchecksapi/blob/rework-scraping/scrape_maints.sh scraping from the CRAN maintainers overview page, but that's slow. 

make sure gabor's /maintainernames route has up to date list of maintainers

**Comment by gaborcsardi** [comment]
crandb is now updated from the rstudio mirror, and the main cran site can have a slightly different set of maintainers.

**Comment by sckott** [comment]
okay, thanks. well it will be up to date **enough**, esp since I don't see much usage of the `/maintainers` route anyway
