### ISSUE TITLE
copy-pasting from Fishbase?

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#40]
There are two occurrences of copy-pasting from Fishbase API docs

https://github.com/ropenscilabs/cchecksapi/blob/master/docs/api_docs.md#response-bodies

https://github.com/ropenscilabs/cchecksapi/blob/master/docs/api_docs.md#heartbeat

**Comment by sckott** [comment]
woopsy! thanks for this

**Comment by sckott** [comment]
thanks @maelle

**Comment by maelle** [comment]
You're welcome! 🙂
