### ISSUE TITLE
CRANCHECK badge not working?

### ISSUE THREAD

**Issue by neonira** [ropensci/cchecksapi#49]
Got one question about CRAN CHECKS **badges** managed by **rOpenSci**. I wonder why I got an unknown badge while official CRAN production is all OK?

URL I use for badge is
https://cranchecks.info/badges/summary/wyz.code.offensiveProgramming
URL I use for production check is
https://cran.r-project.org/web/checks/check_results_wyz.code.offensiveProgramming.html

Any reason for such behavior?
I probably missed a point. Hints are welcome

**Comment by sckott** [comment]
thanks for your question, not sure why you closed it. I didn't account for pkgs having more than one dot in their name. pushing a fix soon, will let you know when it's up

**Comment by sckott** [comment]
its working now https://cranchecks.info/badges/summary/wyz.code.offensiveProgramming

**Comment by neonira** [comment]
Closing issue is just a mistake. Sorry for that. 
Great. Check several of my packages - Seems to work.
Thanks for good and quick fix.
