### ISSUE TITLE
API for maintainers

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/cchecksapi#5]
I.e. these kind of pages:
https://cran.r-project.org/web/checks/check_results_csardi.gabor_at_gmail.com.html

Would be nice. :)

**Comment by sckott** [comment]
sounds good, will try to implement soon

**Comment by sckott** [comment]
getting there, some f*** messy html

**Comment by gaborcsardi** [comment]
No worries, no rush. Thanks much!

**Comment by sckott** [comment]
https://cranchecks.info/maintainers
https://cranchecks.info/maintainers/csardi.gabor_at_gmail.com

**Comment by sckott** [comment]
thoughts, changes?

**Comment by sckott** [comment]
closing but can continue discussion

**Comment by gaborcsardi** [comment]
Looking pretty good, thanks much! 

Why the redundant info? I.e. there is `table`, and `packages`?

Versions are `null`, is that expected? Should these be the package versions?

**Comment by sckott** [comment]
blah, forgot about version, that's a tricky one as it's not even in a html tag at all, will work on that

wrt redundancy, some check pages have a html table and some don't ,e ,.g, 

https://cran.rstudio.com/web/checks/check_results_00gerhard_at_gmail.com.html 
vs. 
https://cran.rstudio.com/web/checks/check_results_1105406k_at_student.gla.ac.uk.html

i guess I could just use the table when it's there, and when not use the other info provided to just have one array of results instead of two

**Comment by gaborcsardi** [comment]
> blah, forgot about version, that's a tricky one as it's not even in a html tag at all, will work on that

Not really crucial, feel free to leave it out.

> wrt redundancy, some check pages have a html table and some don't ,e ,.g,

wow, this is bad. probably a bug. Do you want to ask Kurt? Or do you want me to ask him?

**Comment by sckott** [comment]
okay on version, will try, but probably will not do and if not, will remove that key

on tables, I could ask, but I imagine he'd be more receptive to you than me :) 

p.s. see also #10

**Comment by fmichonneau** [comment]
regarding whether or not there is table on these pages depends on whether the email address is associated with more than one package. It would be nice if it was consistent and a table was always included.

**Comment by sckott** [comment]
There are some maintainer summary pages > 1 pkg, but no table. So it seems somewhat arbitrary. 

@gaborcsardi  Will Kurt be annoyed that we are doing this?  That is, I can message him, but should I talk about what we're doing or just talk about that we'd like for each page to have a summary table?

**Comment by fmichonneau** [comment]
d'oh! Do you have any examples handy? foghorn also scrapes these pages and will most likely fail when it's the case

**Comment by fmichonneau** [comment]
I don't know if Kurt would be annoyed but he wasn't too happy with my "on-demand" scrapping I use with foghorn. And submitting foghorn led to exporting the functions `check_packages_in_dir_details()` and  `CRAN_package_db()` with the release of R 3.4.0!

**Comment by sckott** [comment]
crap, well i think i was wrong, you are right, that there is only a table if >1 pkg. 

but i agree that it would be nice to always have a table

**Comment by sckott** [comment]
Hmm, hopefully he'd be okay with scraping once a day at least which I do here. And its scraping `cran.rstudio.com`, not the main mirror

**Comment by gaborcsardi** [comment]
Yeah, just mention that you want to automate this, and you are scraping the mirror, and it would be nice to always include the table, for easier scraping.

**Comment by sckott** [comment]
Okay

**Comment by sckott** [comment]
emailing with him now. 

Just realized maybe it's better to get maintainer data from this summary page https://cran.r-project.org/web/checks/check_summary_by_maintainer.html#summary_by_maintainer instead of each individual page?

**Comment by sckott** [comment]
Now all maintainer pages (should) have tables (haven't checked many), e.g., 

https://cran.r-project.org/web/checks/check_results_538280_at_gmail.com.html
https://cran.r-project.org/web/checks/check_results_670273197_at_qq.com.html
https://cran.r-project.org/web/checks/check_results_aanota_at_chu-besancon.fr.html

**Comment by gaborcsardi** [comment]
Cool! Good negotiating! :)
