### ISSUE TITLE
should archived pkgs be removed?

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#52]
e.g., i just archived this pkg https://cranchecks.info/pkgs/crevents and the data is still there, i guess each day now has the last day of data that existed?

often though pkgs can be archived by cran, then submitted again, etc.  - so we wouldn't want to lose history for that pkg.

**Comment by sckott** [comment]
~~For email notifications - it'd be ideal i think to skip any pkgs that are archived - would need a foolproof way to sort out if a pkg is archived~~

emails gone

**Comment by maelle** [comment]
https://github.com/ropensci/fulltext also has a CRAN OK badge despite being archived on CRAN.

**Comment by sckott** [comment]
Thanks for letting me know @maelle 

I should probably fix this
