### ISSUE TITLE
Could date updated come earlier

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#58]
Looking at e.g. "https://cranchecks.info/pkgs/rhub/history" I was wondering whether within each slot, "date_updated" could come before "summary"?

**Comment by sckott** [comment]
good idea. should be pretty easy.

**Comment by maelle** [comment]
It's because it'd look better on https://cran-checks-docs.netlify.app/?JavaScript#packages-by-name-history :grin:

**Comment by sckott** [comment]
@maelle fixed

**Comment by maelle** [comment]
Yay, thanks!
