### ISSUE TITLE
Example with shell for notifications token?

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#59]
What would be an example for https://github.com/ropenscilabs/cchecksapi/blob/notifications/docs/api_docs.md#notifications-token?

Especially as there's no endpoint for token in the heartbeat, or I'm missing something obvious?

**Comment by sckott** [comment]
that's the route used in `cchn_register()` function. it's hidden from heartbeat just because i didn't think anyone would use it outside of an R session. its pretty simple, its a GET request like `/notifications/token?email=foo@bar.com` - and the response is always the same as shown in the docs
