### ISSUE TITLE
Add API developer notes somewhere?

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#63]
I.e. your notes on how it all works.

Maybe it could be in the README once the docs website is "deployed" (i.e. has a nice URL and has the docs endpoint pointing to it).

**Comment by sckott** [comment]
you mean like the stuff at the top of the readme https://github.com/ropenscilabs/cchecksapi#cran-check-results-api ?

**Comment by maelle** [comment]
Oh I had missed that sorry! Yeah so this can be closed I suppose 🙂
