### ISSUE TITLE
Should there be an output when deleting rule?

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#65]
When creating rules there's "success" as an output. I'd expect something similar for rule deletion maybe?

**Comment by sckott** [comment]
its typical to have no content in response body on DELETE success, and status code 204 - so i followed that pattern - i think in R it returns `TRUE` on success, and if it fails then raises whatever error happened. does that make sense?

**Comment by maelle** [comment]
it does make sense!
