### ISSUE TITLE
Sign up maintainers of rOpenSci packages to notifications?

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecksapi#72]
Per https://github.com/ropenscilabs/cchecksapi/issues/13#issuecomment-674807907

**Comment by maelle** [comment]
I wonder whether it'd make more sense to document notifications.

Or instead signing them up, but sending an email with clear instructions on how to tweak/ opt out? :thinking:

**Comment by sckott** [comment]
I'd like to sign people up automatically but I have a feeling others on our team may not agree.  Probably best to document it and let people know they can sign up.

**Comment by maelle** [comment]
As a subsection in the curation policy? If so could you edit my PR with some elements about the CRAN checks notifications? https://github.com/ropensci/dev_guide/pull/263

**Comment by sckott** [comment]
hmm, would it belong better in Maintaining Packages section?

**Comment by maelle** [comment]
as a new chapter "Dealing with CRAN?" or so?

**Comment by sckott** [comment]
yeah, prob good idea to have a chapter for cran since its such a PITA. could include various gotchas for cran submission, this api, etc
